#!/usr/bin/env bash
# change local host and add facebook host

cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1/127.0.0.2/g' ~/hosts.new
echo '8.8.8.8		facebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
